### ISSUE TITLE
Strapi Login logout after page refresh

### ISSUE THREAD

**Issue by tobias-srf** [nuxt-modules/strapi#138]
I am having trouble keeping $strapi.user persistent. I can login fine and cookies and local storage is also set, but upon a page request the user gets logged out straight away. 

Is this expected behaviour?

I have tried following:

```
  strapi: {
    url: "http://localhost:8086",
    key: 'authi_jwt',
    expires: '1d',  
    cookie: {}
  },
```
To keep the session from expiring ...

**Comment by kainio** [comment]
I have the same problem and i am getting 403 with `GET /users/me `when checking for `$strapi.user`

**Comment by tobias-srf** [comment]
Hi @benjamincanac I currently don't have any reproduction link, just running localhost. However, I am also using nuxt-i18n and I have noticed that it creates more than one cookie for different urls.

Could this be the issue? When is the GET /users/me called?

![grafik](https://user-images.githubusercontent.com/78744870/117666971-b25b1a80-b1a4-11eb-85ac-048a750c00db.png)

**Comment by kainio** [comment]
@benjamincanac my bad, i created an new role but forgot to add 'User.me'. thanks

**Comment by tobias-srf** [comment]
@benjamincanac I am doing SSR and following code will tell me that I am loged out:

```
export const actions = {
  nuxtServerInit(vc, context) {
    console.log("### nuxtServerInit ###")
    console.log("proxy disabled?")

    if (context.$strapi.user) {
      console.log(context.$strapi.user.username)
    } else {
      console.log("ok not logged in INIT!")
    }
    ...
```

**Comment by tobias-srf** [comment]
@benjamincanac  nothing spectacular here ...

```
<template>
  <div class="w-4/5 mx-auto md:w-1/2 text-center my-12">
    <div v-show="error !== ''" class="p-3 border">
      <p>{{ error }}</p>
    </div>
    <h1 class="font-bold text-2xl md:text-4xl mt-5">Login</h1>
    <form @submit="loginUser">
      <div>
        <input
          v-model="identifier"
          class="p-3 my-5 border w-full"
          type="email"
          placeholder="email"
        />
      </div>
      <div>
        <input
          v-model="password"
          class="p-3 my-5 border w-full"
          type="password"
          placeholder="password"
        />
      </div>
      <div>
        <button
          :disabled="identifier === '' || password === ''"
          class="button--green"
          type="submit"
        >
          Login
        </button>
      </div>
    </form>
  </div>
</template>
<script>
export default {
  data() {
    return {
      identifier: '',
      password: '',
      error: '',
    }
  },
  methods: {
    async loginUser(e) {
      e.preventDefault()
      try {
        const user = await this.$strapi.login({
          identifier: this.identifier,
          password: this.password,
        })
        console.log(user)
        if (user !== null) {
          this.error = ''
          this.$nuxt.$router.push(this.localePath('auth-profile'))
        }
      } catch (error) {
        this.error = 'Error in login credentials'
      }
    },
  }
}
</script>
```

**Comment by tobias-srf** [comment]
@benjamincanac I think I found the issue. I am using docker and run nuxt and strapi on the same instance. I have a port forwarding set aside for either application. If I tell nuxt to use the port forwarded port I get the issue.

If I use the internal url via nuxt 127.0.0.1:1337 I get the /user/me GET call

So it looks like it is a partial network issue ....

**Comment by tobias-srf** [comment]
I guess the issue is that the strapi module does not respect the strapi { url: 0.0.0.0:<port> } settings all the way and gets bogged down when doing authentication requests, but they never reach the strapi endpoint ... So there might be stil a bug ...

**Comment by pixelscript-io** [comment]
@tobias-srf I fixed this issue by completely clearing the application cache (I was using Google Chrome) and modifying my options object to the following:

```javascript
strapi: {
  url: 'https://strapi.mydomain.net',
  key: 'authToken',
  expires: '7d',
  cookie: {
    sameSite: true,
    path: '/'
  }
}
```

Upon inspecting my Network tab when it would redirect me to /login and display I wasn't logged in, I found some duplicate cookies which I'm assuming is what was causing the issue.  I hope this helps!

**Comment by adhamfarrag** [comment]
I applied the same but it still doesn't work for me. @pixelscript-io does the same issue still happen with you after anytime soon ?

**Comment by LucaMargadant** [comment]
> @benjamincanac I think I found the issue. I am using docker and run nuxt and strapi on the same instance. I have a port forwarding set aside for either application. If I tell nuxt to use the port forwarded port for strapi I get the issue.
> 
> If I use the internal url via nuxt 127.0.0.1:1337 I get the /user/me GET call and everything is fine and the user stays logged in!
> 
> So it looks like it is a partial network issue ....

Thank you! For me this worked. Setting an url to the strapi module fixed the issue. While local development the call to strapi was over localhost. Changing strapi's url in nuxt config to http://127.0.0.1:1337 fixed it.

`expires: '30d',
            url: http://127.0.0.1:1337,
            cookie: {
                path: '/',
            },`
